### ISSUE TITLE
No module named pkg_resources

### ISSUE THREAD

**Issue by smruti77** [open-power-host-os/tests#158]
while i am doing python avocado-setup.py --bootstrap
i got the error
```
Traceback (most recent call last):
  File "avocado-setup.py", line 23, in <module>
    import configparser
ImportError: No module named configparser

so tried to install configparser ,

 pip install configparser
Traceback (most recent call last):
  File "/usr/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by PraveenPenguin** [comment]
@smruti77 please install configparser using `pip3 install configparser`  as pip pacakge installation we disabled from repo

**Comment by smruti77** [comment]
@PraveenPenguin getting same error

```Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by PraveenPenguin** [comment]
ah seems me setup issue may be python3 not installed properly

**Comment by smruti77** [comment]
got it, thank you.it resolved.
